<?php

/**
 * @file
 * islandora_solr_realtime_get.module
 *
 *
 *  Copyright 2019 Leiden University Library
 *
 *  This file is part of islandora_solr_realtime_get.
 *
 *  islandora_solr_realtime_get is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

// Permissions.
define('ISLANDORA_SOLR_REALTIME_GET_PERMISSION', 'view solr output');

/**
 * Implements hook_menu().
 */
function islandora_solr_realtime_get_menu() {
  return array(
    'islandora/object/%islandora_object/solr_realtime_get' => array(
      'title' => t('Solr document'),
      'type' => MENU_LOCAL_TASK,
      'page callback' => 'islandora_solr_realtime_get_view',
      'page arguments' => array(2),
      'file' => 'includes/admin.form.inc',
      'access arguments' => array(ISLANDORA_SOLR_REALTIME_GET_PERMISSION),
    ),
  );
}

/**
 * Implements hook_permission().
 */
function islandora_solr_realtime_get_permission() {
  return array(
    ISLANDORA_SOLR_REALTIME_GET_PERMISSION => array(
      'title' => t('View Solr document'),
      'description' => t("View Solr document retrieved via Solr RealTime Get."),
    ),
  );
}
